development:
  adapter: mongodb
  host: localhost
  database: contour_log_devel

test: &TEST
  adapter: mongodb
  host: localhost
  database: contour_log_test

production:
  adapter: mongodb
  host: localhost
  database: contour_log_production

cucumber:
  <<: *TEST